import 'dotenv/config';
import mongoose from 'mongoose';
import { Module } from './models.js';
const modules = [
  ['Computer & IT Fundamentals','FOUNDATION'],['Linux Fundamentals','FOUNDATION'],['Shell Scripting','FOUNDATION'],['Networking Fundamentals','FOUNDATION'],['Git & Version Control','FOUNDATION'],['SQL & Database Fundamentals','INTERMEDIATE'],['Application Support Engineer','INTERMEDIATE'],['Production Support Engineer','PRODUCTION'],['Cloud Computing Fundamentals','INTERMEDIATE'],['AWS Fundamentals to Advanced','ADVANCED'],['Docker','ADVANCED'],['Kubernetes','ADVANCED'],['CI/CD','ADVANCED'],['Infrastructure as Code','ADVANCED'],['Ansible','ADVANCED'],['Nginx & Web Servers','PRODUCTION'],['Monitoring & Observability','PRODUCTION'],['DevSecOps & Security','PRODUCTION'],['Microservices Architecture','PRODUCTION'],['Site Reliability Engineering','PRODUCTION'],['Real World DevOps Projects','INTERVIEW']
];
const topicSets:Record<string,string[]>={
 'Computer & IT Fundamentals':['How computers work','CPU','RAM','Storage','Processes','Threads','Operating systems','Client-server architecture','Applications','Services','Ports','Basic troubleshooting','Hardware vs software','Virtual machines','Cloud computing basics'],
 'Linux Fundamentals':['Linux introduction','Linux distributions','Filesystem hierarchy','pwd','ls','cd','mkdir','touch','cp','mv','rm','cat','less','head','tail','grep','find','locate','sort','uniq','cut','awk','sed','xargs','Pipes','Redirection','Environment variables','PATH','Aliases','Users','Groups','sudo','chmod','chown','File permissions','Symbolic links','Processes','ps','top','htop','kill','Jobs','systemctl','journalctl','Services','Package management','apt','yum','dnf','Disk management','df','du','free','uptime','hostname','uname','cron','crontab','Log files','SSH','SCP','SFTP','Linux troubleshooting'],
 'Shell Scripting':['Bash introduction','Shell vs Bash','Variables','Input','echo','Command substitution','Arithmetic','if','case','for loop','while loop','Functions','Arguments','Exit status','Logical operators','Arrays','File checks','Process checks','Server health scripts','Disk monitoring script','CPU monitoring script','Memory monitoring script','Log monitoring script','Service monitoring script','Backup script','Production troubleshooting scripts'],
 'Networking Fundamentals':['Network basics','LAN','WAN','IP address','IPv4','IPv6','MAC address','Subnet','CIDR','Gateway','DNS','DHCP','TCP','UDP','TCP 3-way handshake','OSI model','TCP/IP model','HTTP','HTTPS','HTTP methods','HTTP status codes','Headers','Cookies','Sessions','Ports','Sockets','SSH','FTP','SFTP','SMTP','traceroute','ping','nslookup','dig','curl','netstat','ss','Firewall','NAT','Proxy','Reverse proxy','Load balancer','CDN','VPN','TLS/SSL','Certificates','Networking troubleshooting'],
 'Git & Version Control':['Git introduction','Git vs GitHub','Repository','git init','git clone','git status','git add','git commit','git push','git pull','git fetch','Branches','Merge','Rebase','Cherry-pick','Stash','Reset','Revert','Tags','Conflicts','.gitignore','GitHub','Pull requests','Code review','GitHub Actions','Branching strategies','Git troubleshooting'],
 'SQL & Database Fundamentals':['Database basics','Relational databases','Tables','Rows','Columns','Primary key','Foreign key','Constraints','SELECT','WHERE','ORDER BY','GROUP BY','HAVING','JOIN','Subqueries','Aggregate functions','Indexes','Transactions','ACID','Normalization','Query optimization','Database connections','Connection pooling','Locks','Deadlocks','Backups','Restore','Replication','PostgreSQL','MySQL','Production database troubleshooting'],
 'AWS Fundamentals to Advanced':['AWS overview','AWS global infrastructure','IAM','Users','Groups','Roles','Policies','EC2','AMI','Instance types','EBS','Snapshots','Security groups','Auto Scaling','Load Balancer','S3','Bucket policies','CloudFront','Route 53','VPC','Subnets','Route tables','Internet gateway','NAT gateway','RDS','DynamoDB','Lambda','ECS','EKS','CloudWatch','CloudTrail','SNS','SQS','Secrets Manager','Systems Manager','AWS CLI','AWS troubleshooting','AWS production support'],
 'Docker':['Containers','Container vs VM','Docker architecture','Docker CLI','docker run','docker ps','docker logs','docker exec','Images','Dockerfile','Layers','Volumes','Networks','Port mapping','Environment variables','Docker Compose','Image optimization','Docker registry','Docker security','Container troubleshooting','Production Docker'],
 'Kubernetes':['Kubernetes introduction','Architecture','Cluster','Control plane','Worker node','Pod','Deployment','ReplicaSet','Service','ClusterIP','NodePort','LoadBalancer','Namespace','ConfigMap','Secret','Labels','Selectors','Liveness probe','Readiness probe','Resource requests','Resource limits','Volumes','Persistent volume','StatefulSet','DaemonSet','Job','CronJob','Ingress','Helm','kubectl','Logs','Describe','Events','Rollout','Rollback','Scaling','HPA','Kubernetes networking','Kubernetes security','Kubernetes troubleshooting','Production Kubernetes']
};
const fallback=['Fundamentals','Architecture','Configuration','Troubleshooting','Production patterns','Monitoring','Security','Incident response','Interview practice'];
async function run(){await mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/devops-support-journey');await Module.deleteMany({});const docs=modules.map(([title,level],i)=>({title,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-'),description:`Master ${title.toLowerCase()} for DevOps, cloud, and support work.`,level,category:level,estimatedDays:4+(i%8),order:i+1,topics:(topicSets[title]||fallback).map((name,j)=>({title:name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),description:`Understand ${name.toLowerCase()} and apply it to reliable production systems.`,difficulty:j>8?'Intermediate':'Beginner',estimatedMinutes:30+(j%4)*15,learningSteps:[{title:'Watch recommended learning material',completed:false},{title:'Read documentation or reference',completed:false},{title:'Explain the concept in your own words',completed:false},{title:'Answer an interview-style question',completed:false}],resources:[{name:'Official documentation',type:'Official docs',url:'https://www.kernel.org/doc/html/latest/',free:true}],interviewQuestions:[`How would you explain ${name} and troubleshoot it in production?`],order:j+1}))}));await Module.insertMany(docs);console.log(`Seeded ${docs.length} modules and ${docs.reduce((n,m)=>n+m.topics.length,0)} topics`);await mongoose.disconnect()}run().catch(error=>{console.error(error);process.exit(1)});
